spring.application.name=Booking-Room

spring.jpa.hibernate.ddl-auto=update
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.url=jdbc:postgresql://localhost:5432/booking_room

api.security.token.secret=PALMEIRAS